# Generated by Django 2.2 on 2020-12-01 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201202_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, related_name='group', to='posts.Group'),
        ),
    ]
